apiVersion: apps/v1
kind: Deployment
metadata:
  name: edog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edog-backend
  template:
    metadata:
      labels:
        app: edog-backend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret    
      containers:
      - name: edog-backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: Always
        env:
        - name: SMTP_HOST
          value: {{ .Values.backend.config.smtp_host }}
        - name: SMTP_PORT
          value: {{ .Values.backend.config.smtp_port | quote  }}
        - name: SMTP_USER
          value: {{ .Values.backend.config.smtp_user }}
        - name: SMTP_PASS
          value: {{ .Values.backend.config.smtp_pass }}
        - name: DATABASE_URL
          value: "postgresql://postgres:P@ssw0rd@192.168.1.200:5432/edog_db"
        - name: DB_PORT
          value: "5432"
        - name: JWT_SECRET
          value: {{ .Values.backend.config.jwt_secret | quote }}
        - name: JWT_EXPIRES_IN
          value: {{ .Values.backend.config.jwt_expires_in | quote }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        volumeMounts:
        - name: edog-uploads      # Mount this volume
          mountPath: /app/uploads # Path in the container
      volumes:
      - name: edog-uploads
        hostPath:
          path: /home/home/edog      # Path on the host machine
          type: DirectoryOrCreate  