{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edog-frontend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.frontend.ingress.issuer }}"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: {{ .Values.frontend.ingress.className }}

  tls:
    - hosts:
{{- range .Values.frontend.ingress.hosts }}
        - "{{ . }}"
{{- end }}
      secretName: edog-frontend-tls

  rules:
{{- range .Values.frontend.ingress.hosts }}
    - host: "{{ . }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
{{- end }}

{{- end }}