apiVersion: v1
kind: Service
metadata:
  name: edog-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: edog-frontend