apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuaWtvbGF5LnBlc2hldkBnbWFpbC5jb20iLCJwYXNzd29yZCI6Ijg2MTIyMzcyMjciLCJlbWFpbCI6Im5pa29sYXkucGVzaGV2QGdtYWlsLmNvbSIsImF1dGgiOiJibWxyYjJ4aGVTNXdaWE5vWlhaQVoyMWhhV3d1WTI5dE9qZzJNVEl5TXpjeU1qYz0ifX19