import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Download, Printer as Print, ArrowLeft, Heart } from 'lucide-react';
import { formatDate } from '../lib/utils';
import { apiClient } from '../lib/api';
import { useApp } from '../context/AppContext';

interface PetPassportProps {
  dog: any;
  onNavigate: (view: string) => void;
}

export const PetPassport: React.FC<PetPassportProps> = ({ dog, onNavigate }) => {
  const { t } = useTranslation();
  const { user } = useApp();
  const [vaccinations, setVaccinations] = useState<any[]>([]);
  const [healthRecords, setHealthRecords] = useState<any[]>([]);
  const [appointments, setAppointments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadPassportData();
  }, [dog?.id]);

  const loadPassportData = async () => {
    if (!dog?.id) return;
    try {
      const [vacRes, healthRes] = await Promise.all([
        apiClient.getVaccinations(dog.id),
        apiClient.getHealthRecords(dog.id),
      ]);
      setVaccinations(vacRes.vaccinations);
      setHealthRecords(healthRes.healthRecords);
    } catch (err) {
      console.error('Error loading passport data:', err);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => window.print();

  const handleDownload = async () => {
    const el = document.getElementById('passport-content');
    if (!el) return;
    try {
      const canvas = await html2canvas(el, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        logging: false,
      });
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4', compress: true });
      const imgData = canvas.toDataURL('image/png');
      const pw = pdf.internal.pageSize.getWidth();
      const ph = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const ratio = Math.min((pw - margin * 2) / canvas.width, (ph - margin * 2) / canvas.height);
      const sw = canvas.width * ratio;
      const sh = canvas.height * ratio;
      pdf.addImage(imgData, 'PNG', (pw - sw) / 2, margin, sw, sh);
      pdf.setFontSize(8);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated by eDog • ${new Date().toLocaleDateString()}`, pw / 2, ph - 5, { align: 'center' });
      pdf.save(`${dog.name}-passport.pdf`);
    } catch (err) {
      console.error('PDF error:', err);
    }
  };

  if (!dog) {
    return (
      <div className="font-jakarta p-8 text-center">
        <p className="text-gray-500 dark:text-[#8b919d]">{t('noData')}</p>
        <button onClick={() => onNavigate('dashboard')} className="mt-4 text-[#005da7] dark:text-[#a4c9ff] text-sm font-medium">
          ← {t('dashboard')}
        </button>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="font-jakarta min-h-screen bg-[#fbf9f8] dark:bg-[#111316] flex items-center justify-center">
        <div className="text-center">
          <div className="w-10 h-10 border-2 border-[#005da7] dark:border-[#a4c9ff] border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          <p className="text-gray-500 dark:text-[#8b919d] text-sm">{t('loading')}</p>
        </div>
      </div>
    );
  }

  const rabiesVacs = vaccinations.filter(v => v.vaccine_name?.toLowerCase().includes('rabies'));
  const otherVacs = vaccinations.filter(v => !v.vaccine_name?.toLowerCase().includes('rabies'));

  // Next upcoming vaccination expiry for reminders
  const expiringSoon = vaccinations
    .filter(v => v.next_due_date)
    .sort((a, b) => new Date(a.next_due_date).getTime() - new Date(b.next_due_date).getTime())
    .slice(0, 2);

  const cardClass = 'bg-white dark:bg-[#1d2026] border border-gray-100 dark:border-[#2d3540] rounded-xl';
  const labelClass = 'text-xs font-semibold text-gray-500 dark:text-[#8b919d] uppercase tracking-wide mb-0.5';
  const valueClass = 'text-sm font-medium text-gray-900 dark:text-[#e1e2eb]';

  return (
    <div className="font-jakarta bg-[#fbf9f8] dark:bg-[#111316] min-h-full p-4 sm:p-6 lg:p-8">
      <div id="passport-content" className="max-w-[1280px] mx-auto space-y-5 lg:space-y-6">

        {/* Page header */}
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <button
              onClick={() => onNavigate('dashboard')}
              className="flex items-center gap-1.5 text-sm text-gray-500 dark:text-[#8b919d] hover:text-[#005da7] dark:hover:text-[#a4c9ff] mb-3 transition-colors"
            >
              <ArrowLeft size={15} />
              {t('dashboard')}
            </button>
            <h1 className="text-2xl sm:text-3xl font-bold text-[#005da7] dark:text-[#a4c9ff]">
              {dog.name}'s {t('petPassport')}
            </h1>
            <p className="text-gray-500 dark:text-[#8b919d] mt-1 text-sm">
              {dog.breed}{dog.age ? ` • ${dog.age} ${t('yearsOld')}` : ''}{dog.passportNumber ? ` • ID: #${dog.passportNumber}` : ''}
            </p>
          </div>
          <div className="flex gap-2 flex-shrink-0 no-print">
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-2 border border-gray-200 dark:border-[#414751] rounded-xl text-sm font-medium text-gray-700 dark:text-[#c1c7d3] hover:bg-gray-50 dark:hover:bg-[#282a2d] transition-colors"
            >
              <Print size={15} />{t('print')}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2 bg-[#005da7] dark:bg-[#a4c9ff] text-white dark:text-[#00315d] rounded-xl text-sm font-medium hover:opacity-90 transition-opacity"
            >
              <span className="material-symbols-outlined text-base leading-none">picture_as_pdf</span>
              {t('download')}
            </button>
          </div>
        </div>

        {/* Bento grid */}
        <div className="grid grid-cols-12 gap-4 lg:gap-6">

          {/* ── LEFT COLUMN ── */}
          <div className="col-span-12 md:col-span-8 space-y-4 lg:space-y-6">

            {/* Hero card */}
            <div className={`${cardClass} p-5 sm:p-6 relative overflow-hidden`}>
              {/* Ambient glow */}
              <div className="absolute -top-20 -right-20 w-56 h-56 bg-[#005da7]/10 dark:bg-[#a4c9ff]/10 blur-[80px] rounded-full pointer-events-none" />

              <div className="flex flex-col sm:flex-row gap-5 relative z-10">
                {/* Dog photo */}
                <div className="w-full sm:w-36 h-44 sm:h-36 rounded-xl overflow-hidden border-2 border-[#005da7]/20 dark:border-[#a4c9ff]/20 flex-shrink-0 shadow-lg">
                  {dog.profilePicture ? (
                    <img src={dog.profilePicture} alt={dog.name} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full bg-gradient-to-br from-[#005da7]/20 to-[#0090e7]/20 dark:from-[#a4c9ff]/10 dark:to-[#005da7]/10 flex items-center justify-center">
                      <Heart size={40} className="text-[#005da7]/40 dark:text-[#a4c9ff]/40" />
                    </div>
                  )}
                </div>

                {/* Info */}
                <div className="flex-1">
                  <div className="flex flex-wrap gap-2 mb-3">
                    <span className="px-2.5 py-1 bg-[#005da7]/10 dark:bg-[#a4c9ff]/20 text-[#005da7] dark:text-[#a4c9ff] rounded-full text-xs font-semibold border border-[#005da7]/20 dark:border-[#a4c9ff]/30">
                      {t('active')}
                    </span>
                    {vaccinations.length > 0 && (
                      <span className="px-2.5 py-1 bg-gray-100 dark:bg-[#32353c] text-gray-600 dark:text-[#c1c7d3] rounded-full text-xs font-medium">
                        Travel Ready
                      </span>
                    )}
                  </div>

                  <h3 className="text-lg font-semibold text-gray-900 dark:text-[#e1e2eb] mb-1">{t('healthSummary')}</h3>
                  <p className="text-sm text-gray-500 dark:text-[#8b919d] leading-relaxed mb-4">
                    {dog.name} {vaccinations.length > 0
                      ? `has ${vaccinations.length} vaccination${vaccinations.length !== 1 ? 's' : ''} on record.`
                      : 'has no vaccinations recorded yet.'}{' '}
                    {healthRecords.length > 0
                      ? `${healthRecords.length} health record${healthRecords.length !== 1 ? 's' : ''} available.`
                      : ''}
                  </p>

                  {/* Quick stats row */}
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                    {[
                      { label: t('weight'), value: dog.weight ? `${dog.weight} kg` : '—' },
                      { label: t('breed'), value: dog.breed || '—' },
                      { label: t('sex'), value: dog.sex || '—' },
                      { label: t('microchip'), value: dog.microchipId ? dog.microchipId.slice(0, 8) + '…' : t('notRegistered') },
                    ].map(({ label, value }) => (
                      <div key={label} className="bg-gray-50 dark:bg-[#191c22] rounded-lg p-2.5">
                        <p className={labelClass}>{label}</p>
                        <p className={`${valueClass} truncate`}>{value}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Medical History */}
            <div className={`${cardClass} p-5 sm:p-6`}>
              <div className="flex items-center justify-between mb-5">
                <h3 className="text-base font-semibold text-gray-900 dark:text-[#e1e2eb] flex items-center gap-2">
                  <span className="material-symbols-outlined text-[#005da7] dark:text-[#a4c9ff] text-[20px]">history</span>
                  {t('healthTimeline')}
                </h3>
                <button
                  onClick={() => onNavigate('health')}
                  className="text-xs text-[#005da7] dark:text-[#a4c9ff] font-semibold hover:opacity-80"
                >
                  {t('viewAll')}
                </button>
              </div>

              {healthRecords.length > 0 ? (
                <div className="space-y-3">
                  {healthRecords
                    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                    .slice(0, 5)
                    .map(record => (
                      <div
                        key={record.id}
                        className="flex gap-3 p-3 bg-gray-50 dark:bg-[#191c22] rounded-xl border border-gray-100 dark:border-[#414751]/30"
                      >
                        <div className="w-9 h-9 bg-[#005da7]/10 dark:bg-[#a4c9ff]/10 rounded-full flex items-center justify-center flex-shrink-0">
                          <span className="material-symbols-outlined text-[#005da7] dark:text-[#a4c9ff] text-[18px]">health_and_safety</span>
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start justify-between gap-2">
                            <p className="text-sm font-medium text-gray-900 dark:text-[#e1e2eb] truncate">{record.title}</p>
                            <span className="text-xs text-gray-400 dark:text-[#8b919d] flex-shrink-0">{formatDate(record.date)}</span>
                          </div>
                          <p className="text-xs text-gray-500 dark:text-[#8b919d] mt-0.5 capitalize">
                            {record.type?.replace('-', ' ')}
                            {record.veterinarian ? ` • ${record.veterinarian}` : ''}
                          </p>
                        </div>
                      </div>
                    ))}
                </div>
              ) : (
                <div className="text-center py-8">
                  <span className="material-symbols-outlined text-gray-300 dark:text-[#414751] text-4xl">health_and_safety</span>
                  <p className="text-sm text-gray-500 dark:text-[#8b919d] mt-2">{t('noHealthRecords')}</p>
                </div>
              )}
            </div>

            {/* Pet Details section (for PDF / print) */}
            <div className={`${cardClass} p-5 sm:p-6`}>
              <h3 className="text-base font-semibold text-gray-900 dark:text-[#e1e2eb] flex items-center gap-2 mb-5">
                <span className="material-symbols-outlined text-[#005da7] dark:text-[#a4c9ff] text-[20px]">pets</span>
                {t('petDetails')}
              </h3>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {[
                  { label: t('name'), value: dog.name },
                  { label: t('species'), value: 'Dog' },
                  { label: t('breed'), value: dog.breed },
                  { label: t('sex'), value: dog.sex },
                  { label: t('dateOfBirth'), value: dog.dateOfBirth ? formatDate(dog.dateOfBirth) : t('notSpecified') },
                  { label: t('colour'), value: dog.colour || '—' },
                  { label: t('weight'), value: dog.weight ? `${dog.weight} kg` : '—' },
                  { label: t('passportNumber'), value: dog.passportNumber || '—' },
                  { label: t('notableFeatures'), value: dog.features || '—' },
                ].map(({ label, value }) => (
                  <div key={label} className="bg-gray-50 dark:bg-[#191c22] rounded-lg p-3">
                    <p className={labelClass}>{label}</p>
                    <p className={valueClass}>{value}</p>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* ── RIGHT COLUMN ── */}
          <div className="col-span-12 md:col-span-4 space-y-4 lg:space-y-6">

            {/* Vaccinations */}
            <div className={`${cardClass} p-5`}>
              <div className="flex items-center gap-2 mb-5">
                <span className="material-symbols-outlined text-[#005da7] dark:text-[#a4c9ff] text-[20px]">vaccines</span>
                <h3 className="text-base font-semibold text-gray-900 dark:text-[#e1e2eb]">{t('vaccinations')}</h3>
              </div>

              {vaccinations.length === 0 ? (
                <p className="text-sm text-gray-500 dark:text-[#8b919d] text-center py-4">{t('noOtherVaccinations')}</p>
              ) : (
                <div className="space-y-4">
                  {vaccinations.map(v => {
                    const isExpired = v.next_due_date && new Date(v.next_due_date) < new Date();
                    const isDueSoon = v.next_due_date && !isExpired &&
                      (new Date(v.next_due_date).getTime() - Date.now()) < 30 * 24 * 60 * 60 * 1000;
                    const accentColor = isExpired
                      ? 'bg-red-500'
                      : isDueSoon
                      ? 'bg-amber-400'
                      : 'bg-[#005da7] dark:bg-[#a4c9ff]';

                    return (
                      <div key={v.id} className="relative pl-3">
                        <div className={`absolute left-0 top-0 bottom-0 w-1 rounded-full ${accentColor}`} />
                        <div className="flex justify-between items-start">
                          <div>
                            <p className="text-sm font-medium text-gray-900 dark:text-[#e1e2eb]">{v.vaccine_name}</p>
                            <p className="text-xs text-gray-400 dark:text-[#8b919d]">
                              {t('dateGiven')}: {formatDate(v.date_given)}
                            </p>
                          </div>
                          <div className="text-right flex-shrink-0 ml-2">
                            <p className={`text-xs font-bold ${
                              isExpired ? 'text-red-500' :
                              isDueSoon ? 'text-amber-500' :
                              'text-[#005da7] dark:text-[#a4c9ff]'
                            }`}>
                              {isExpired ? 'Expired' : isDueSoon ? 'Due soon' : t('validUntil')}
                            </p>
                            <p className="text-xs text-gray-500 dark:text-[#8b919d]">
                              {v.next_due_date ? formatDate(v.next_due_date) : '—'}
                            </p>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}

              <button
                onClick={() => onNavigate('health')}
                className="w-full mt-5 py-2 border border-gray-200 dark:border-[#414751] rounded-xl text-xs font-medium text-gray-600 dark:text-[#c1c7d3] hover:bg-gray-50 dark:hover:bg-[#282a2d] transition-colors"
              >
                {t('addVaccination')}
              </button>
            </div>

            {/* Owner details */}
            <div className={`${cardClass} p-5`}>
              <div className="flex items-center gap-2 mb-5">
                <span className="material-symbols-outlined text-[#005da7] dark:text-[#a4c9ff] text-[20px]">person</span>
                <h3 className="text-base font-semibold text-gray-900 dark:text-[#e1e2eb]">{t('ownerDetails')}</h3>
              </div>
              <div className="space-y-3">
                {[
                  { label: t('name'), value: user?.name || '—' },
                  { label: t('email'), value: user?.email || '—' },
                  { label: t('telephone'), value: (user as any)?.phone || '—' },
                  { label: t('issuedBy'), value: t('bulgarianFoodSafetyAgency') },
                  { label: t('dateOfIssue'), value: formatDate(dog.createdAt) },
                ].map(({ label, value }) => (
                  <div key={label} className="bg-gray-50 dark:bg-[#191c22] rounded-lg p-3">
                    <p className={labelClass}>{label}</p>
                    <p className={`${valueClass} break-all`}>{value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Microchip */}
            <div className={`${cardClass} p-5`}>
              <div className="flex items-center gap-2 mb-4">
                <span className="material-symbols-outlined text-[#005da7] dark:text-[#a4c9ff] text-[20px]">memory</span>
                <h3 className="text-base font-semibold text-gray-900 dark:text-[#e1e2eb]">{t('petMarking')}</h3>
              </div>
              <div className="space-y-3">
                <div className="bg-gray-50 dark:bg-[#191c22] rounded-lg p-3">
                  <p className={labelClass}>{t('microchipCode')}</p>
                  <p className="font-mono text-sm font-bold text-gray-900 dark:text-[#e1e2eb]">
                    {dog.microchipId || t('notRegistered')}
                  </p>
                  <p className="text-xs text-gray-400 dark:text-[#8b919d] mt-0.5">ISO 11784/11785</p>
                </div>
                <div className="bg-gray-50 dark:bg-[#191c22] rounded-lg p-3">
                  <p className={labelClass}>{t('microchipLocation')}</p>
                  <p className={valueClass}>{t('microchipLocationStandard')}</p>
                </div>
              </div>
            </div>

          </div>
        </div>

        {/* Reminders strip */}
        {expiringSoon.length > 0 && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {expiringSoon.map((v, i) => {
              const isExpired = new Date(v.next_due_date) < new Date();
              return (
                <div
                  key={v.id}
                  className={`${cardClass} p-4 flex items-center gap-3 ${
                    isExpired ? 'border-l-4 border-l-red-500' :
                    i === 0 ? 'border-l-4 border-l-[#005da7] dark:border-l-[#a4c9ff]' : ''
                  }`}
                >
                  <span className={`material-symbols-outlined text-2xl flex-shrink-0 ${
                    isExpired ? 'text-red-500' : 'text-[#005da7] dark:text-[#a4c9ff]'
                  }`}>
                    {isExpired ? 'priority_high' : 'event_note'}
                  </span>
                  <div>
                    <p className="text-sm font-medium text-gray-900 dark:text-[#e1e2eb]">{v.vaccine_name}</p>
                    <p className={`text-xs ${isExpired ? 'text-red-500' : 'text-gray-500 dark:text-[#8b919d]'}`}>
                      {isExpired ? 'Expired' : t('validUntil')}: {formatDate(v.next_due_date)}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        )}

      </div>
    </div>
  );
};
